Repository NGINXcellent/webserv, pull requests merged in 2023-07, with the labels that each got.

#8 3 build the makefile
  .gitignore
  Makefile
  srcs/main.cpp
  tests/CMakeLists.txt
  tests/InputTests/CMakeLists.txt
  tests/InputTests/InputTests.cpp
Labels: enhancement

#9 3 build the makefile
  Makefile
  include/input/InputHandler.hpp
  main.cpp
  src/input/InputHandler.cpp
  src/main.cpp
  tests/CMakeLists.txt
  tests/InputTests/InputTests.cpp
Labels: enhancement

#10 5 creating the code base for mvp1
  .gitignore
  Makefile
  inc/socketClass.hpp
  src/main.cpp
  src/socketClass.cpp
Labels: MVP1

#12 7 multiple connection handling
  Makefile
  inc/socketClass.hpp
  src/main.cpp
  src/socketClass.cpp
Labels: MVP1

#13 11 basic http request and resposnse
  Makefile
  include/http/HttpRequest.hpp
  include/http/HttpRequestFactory.hpp
  include/http/HttpResponse.hpp
  include/http/HttpResponseFactory.hpp
  include/http/MimeType.hpp
  include/http/Server.hpp
  src/http/HttpRequest.cpp
  src/http/HttpRequestFactory.cpp
  src/http/HttpResponse.cpp
  src/http/HttpResponseFactory.cpp
  src/http/MimeType.cpp
  src/http/Server.cpp
  src/main.cpp
  static_pages/index.html
  static_pages/space.jpg
  static_pages/webserv.pdf
Labels: enhancement, MVP1

#19 16 port the server and http classes to new tcp logic refactor classes
  Makefile
  include/http/Server.hpp
  include/socket/TcpServerSocket.hpp
  src/http/MimeType.cpp
  src/http/Server.cpp
  src/main.cpp
  src/socket/TcpServerSocket.cpp
Labels: MVP1
